language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install ipykernel==4.6.1 jupyter_client==5.1.0 nbformat==4.4.0 nbconvert==5.3.1
script:
  - python -W ignore::DeprecationWarning tools/notebooks_test.py -v

#dependencies:
  #- python=3
  #- pip:
    #- numpy
    #- webdriverdownloader
    #- selenium
    
